### PR TITLE
Add basic CI

### PR DESCRIPTION
**Pull request by brainstorm**
*Description of changes:* Add continuous integration via GHA to catch issues like #2 early.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by brainstorm** [comment]
@nmoutschen I guess you noticed already, but I'll be explicit: I'd suggest not merging this until issue #2 is fixed, because it also fails on CI anyway, see: https://github.com/brainstorm/serverless-rust-demo/runs/3762807603#step:9:91

**Comment by nmoutschen** [comment]
I've added `gcc-aarch64-linux-gnu`, which fixes the CI.

For issues in #2 and more, I need to continue experimenting on setting up and/or using the right toolchain for cross--compilation.

**Comment by bnusunny** [comment]
For musl builds, check out https://musl.cc/. Works pretty well.

**Comment by brainstorm** [comment]
> For musl builds, check out https://musl.cc/. Works pretty well.

Check https://github.com/awslabs/aws-lambda-rust-runtime/discussions/306... MUSL introduces unnecessary static bloat when `provided.al2` already supports native GLIBC binaries, plus you can relatively easily change the allocator to optimize performance further.

**Pull request merged**
